import {describe,it,expect} from 'vitest';
import {demoWorkspace} from '../src/core/components';
import {assertWorkspace,normalizeMetrics} from '../src/core/validation';
import {packageWorkspace,importFile} from '../src/core/packages';
import {defaultDisplayFields,contentFields,displayOptions,fitDisplayFields,secondaryOptions} from '../src/core/display';
import {groupingIntent,GROUP_EDGE_INSET,GROUP_CENTER_HOLD} from '../src/core/gestures';
import {formatQuantity} from '../src/core/presentation';
import type {Metric} from '../src/core/model';
const metric:Metric={id:'main',name:'下载',kind:'range',value:999,max:1000,unit:'files',meaning:'completed',status:'running',secondary:[{id:'rate',role:'speed',label:'传输速度',value:541575.37,unit:'bytes_per_second'}]};
describe('optional card display preferences',()=>{
  it('keeps legacy defaults and never automatically selects new metrics',()=>{const card=demoWorkspace().cards[0];expect(card.displayPreferences).toBeUndefined();expect(defaultDisplayFields(card,metric)).not.toContain('metric:extra');expect(displayOptions(card,metric,[metric,{id:'extra',name:'额外字段',kind:'counter',value:99}])).toEqual(expect.arrayContaining([expect.objectContaining({id:'metric:extra'})]));});
  it('preserves selected order, ignores unavailable fields and keeps raw precision',()=>{const card={...demoWorkspace().cards[0],metricId:'main',renderer:'bar' as const,displayPreferences:{fields:['secondary:rate','value','metric:missing','progress']}};const fields=contentFields(card,{metrics:[metric]},Date.now());expect(fields.map(f=>f.id)).toEqual(['secondary:rate','value','progress']);expect(fields[1].items[0].text).toBe('99.9%');expect(metric.secondary![0].value).toBe(541575.37);expect(card.displayPreferences.fields).toContain('metric:missing');});
  it('supports bare graphics and an intentionally empty visual card',()=>{const card={...demoWorkspace().cards[0],metricId:'main',renderer:'ring' as const,displayPreferences:{fields:['progress']}};expect(contentFields(card,{metrics:[metric]},Date.now()).map(f=>f.kind)).toEqual(['graphic']);card.displayPreferences.fields=[];expect(contentFields(card,{metrics:[metric]},Date.now())).toEqual([]);});
  it('keeps the selected numeric ring centre without duplicating its value',()=>{const card={...demoWorkspace().cards[0],metricId:'main',renderer:'ring' as const,ringCenter:'value' as const,displayPreferences:{fields:['icon','value','progress']}};const fields=contentFields(card,{metrics:[metric]},Date.now(),'compact');expect(fields).toHaveLength(1);expect(fields[0]).toMatchObject({id:'value',kind:'graphic',items:[{text:'99.9%',ratio:.999}]});expect(contentFields({...card,ringCenter:'icon'},{metrics:[metric]},Date.now())).toHaveLength(2);});
  it('keeps elapsed percentages for time ranges using the numeric renderer',()=>{const now=Date.parse('2026-10-07T12:00:00Z'),timed:Metric={id:'main',name:'时间',kind:'time_range',start:'2026-10-07T00:00:00Z',end:'2026-10-08T00:00:00Z'},card={...demoWorkspace().cards[0],metricId:'main',renderer:'number' as const,displayPreferences:{fields:['value']}};expect(contentFields(card,{metrics:[timed]},now)[0].items[0].text).toBe('50%');});
  it('roundtrips fields independently for cards sharing an instance',async()=>{const w=demoWorkspace();w.cards[0].displayPreferences={fields:['icon','progress','secondary:rate','metric:temporarily-absent']};w.cards.push({...w.cards[0],id:'another',displayPreferences:{fields:['title','value']}});assertWorkspace(w);const imported=(await importFile('display.progresspack',new Uint8Array(await packageWorkspace(w)).buffer)).workspace!;expect(imported.cards[0].displayPreferences).toEqual(w.cards[0].displayPreferences);expect(imported.cards.at(-1)?.displayPreferences).toEqual({fields:['title','value']});});
  it('rejects malformed, duplicate or executable fields',()=>{const w=demoWorkspace();for(const fields of [['value','value'],['javascript:alert(1)'],[false]]){w.cards[0].displayPreferences={fields:fields as string[]};expect(()=>assertWorkspace(w)).toThrow('显示字段');}});
  it('accepts stable auxiliary labels without inferring unknown lifecycle semantics',()=>{const result=normalizeMetrics([metric]);expect(secondaryOptions(result[0])[0]).toMatchObject({id:'secondary:rate',label:'传输速度'});expect(normalizeMetrics([{...metric,secondary:[{id:'pending',label:'Agent 原始值',role:'failedFiles',value:42}]}])[0].status).toBe('running');expect(()=>normalizeMetrics([{...metric,secondary:[{role:'speed',value:null}]}])).toThrow('辅助');});
  it('never formats a nonzero tiny number as zero',()=>{expect(formatQuantity(.00000012,'s').value).not.toBe('0');expect(formatQuantity(0,'s').value).toBe('0');});
});
describe('measured local field budgeting',()=>{
  it('fits all sixteen rectangular capacities without mutating the selected fields',()=>{const fields=[{id:'value',height:46,width:90},{id:'progress',height:104,width:104},...Array.from({length:10},(_,i)=>({id:`aux-${i}`,height:46,width:100}))],saved=structuredClone(fields);for(let x=1;x<=4;x++)for(let y=1;y<=4;y++){const width=x*160+(x-1)*16-26,height=y*160+(y-1)*16-66,cols=width>436?2:1,chosen=fitDisplayFields(fields,width,height,cols);const rows=chosen.reduce<number[]>((acc,id,index)=>{const row=Math.floor(index/cols);acc[row]=Math.max(acc[row]??0,fields.find(f=>f.id===id)!.height);return acc;},[]);expect(rows.reduce((a,b)=>a+b,0)+(rows.length-1)*8).toBeLessThanOrEqual(height);expect(chosen[0]).toBe('value');}expect(fields).toEqual(saved);});
  it('hides a whole long numeric field and restores it after widening',()=>{const fields=[{id:'long',height:24,width:420},{id:'short',height:24,width:70}];expect(fitDisplayFields(fields,130,100)).toEqual(['short']);expect(fitDisplayFields(fields,500,100)).toEqual(['long','short']);});
  it('retains admitted fields near thresholds and readmits with headroom',()=>{const fields=[{id:'one',height:40,width:60}];expect(fitDisplayFields(fields,100,42)).toEqual([]);expect(fitDisplayFields(fields,100,42,1,['one'])).toEqual(['one']);expect(fitDisplayFields(fields,100,46)).toEqual(['one']);expect(fitDisplayFields(fields,100,39,1,['one'])).toEqual([]);});
  it('allows integer scroll-width rounding inside fractional column widths',()=>{expect(fitDisplayFields([{id:'rounded',height:20,width:134}],133.4,50)).toEqual(['rounded']);});
  it('uses a fixed pixel interior on tall and wide cards, preserving the hold',()=>{for(const [width,height] of [[160,720],[720,160]]){const target=[{id:'long',left:100,top:100,width,height}],point={x:100+GROUP_EDGE_INSET+1,y:100+GROUP_EDGE_INSET+1};const entry=groupingIntent(point,target,{x:point.x,y:50},{},0);expect(entry.centerAt).toBe(0);expect(groupingIntent(point,target,point,entry,GROUP_CENTER_HOLD).target).toBe('long');const edge={...point,x:100+GROUP_EDGE_INSET-1};expect(groupingIntent(edge,target,point,entry,200).target).toBeUndefined();}});
});
