import { describe, it, expect } from 'vitest';
import { webcrypto as crypto, randomUUID } from 'node:crypto';
import { mkdtemp, rm, readFile, stat } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createServer } from 'node:http';
import { once } from 'node:events';
import { PairingAgent, createPairingMiddleware } from '../scripts/pairing-agent.mjs';
const observed='2026-10-07T12:00:00Z', raw={account:{key:'a'.repeat(64),maskedEmail:'t***@e***.com',plan:'plus'},limits:{rateLimits:{primary:{usedPercent:25,windowDurationMins:300,resetsAt:1791381600}}},observedAt:observed};
const binding={schema:'progress/workspace/v1',cards:[{id:'card'}],instances:[{id:'instance'}],connections:[{id:'conn',providerId:'codex',reconnect:true}]};
const enc=v=>Buffer.from(v).toString('base64'),dec=v=>Buffer.from(v,'base64'),utf8=v=>new TextEncoder().encode(v);
async function device(){const keys=await crypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},false,['sign','verify']);return {id:randomUUID(),keys,publicKey:enc(await crypto.subtle.exportKey('spki',keys.publicKey))};}
async function signed(d,action,fields={}) {const payload={action,...fields,deviceId:d.id,timestamp:Date.now(),nonce:randomUUID()};return {...payload,signature:enc(await crypto.subtle.sign({name:'ECDSA',hash:'SHA-256'},d.keys.privateKey,utf8(JSON.stringify(payload))))};}
async function encrypted(endpoint,publicKey,payload){const peer=await crypto.subtle.importKey('spki',dec(publicKey),{name:'ECDH',namedCurve:'P-256'},false,[]),keys=await crypto.subtle.generateKey({name:'ECDH',namedCurve:'P-256'},false,['deriveKey']),key=await crypto.subtle.deriveKey({name:'ECDH',public:peer},keys.privateKey,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);const keyText=enc(await crypto.subtle.exportKey('spki',keys.publicKey)),timestamp=Date.now(),iv=crypto.getRandomValues(new Uint8Array(12)),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:utf8(`${keyText}:${timestamp}`)},key,utf8(JSON.stringify(payload)));const result=await (await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({key:keyText,timestamp,iv:enc(iv),cipher:enc(cipher)})})).json();return JSON.parse(new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:dec(result.iv),additionalData:utf8('response')},key,dec(result.cipher))));}
async function setup(test){const directory=await mkdtemp(join(tmpdir(),'progress-pairing-'));const agent=new PairingAgent({usage:async()=>raw},{directory});await agent.ready;try{await test(agent,directory);}finally{agent.close();await rm(directory,{recursive:true,force:true});}}
async function share(agent){return agent.owner('share',{connection:{id:'conn',providerId:'codex',accountKey:raw.account.key},binding},'http://127.0.0.1:5190/progress-relay/v1');}
describe('one-time, source-approved device pairing',()=>{
  it('contains only ephemeral discovery metadata and invalidates a renewed token',async()=>setup(async agent=>{const first=await share(agent),second=await share(agent);expect(JSON.stringify(second)).not.toMatch(/accountKey|maskedEmail|apiKey|refreshToken|cookie/);expect(second.token).not.toBe(first.token);expect(second.expiresAt-Date.now()).toBeLessThanOrEqual(120000);const d=await device();await expect(agent.handle(await signed(d,'claim',{token:first.token,label:'测试手机',publicKey:d.publicKey}))).rejects.toThrow('过期');}));
  it('requires source approval, consumes the token, rejects replay, and enforces revocation',async()=>setup(async agent=>{const code=await share(agent),d=await device(),request=await signed(d,'claim',{token:code.token,label:'测试手机',publicKey:d.publicKey}),claim=await agent.handle(request);expect(claim.state).toBe('pending');await expect(agent.handle(request)).rejects.toThrow('重复');await expect(agent.handle(await signed(d,'snapshot',{connectionId:'conn'}))).rejects.toThrow('未获授权');await expect(agent.handle(await signed(await device(),'claim',{token:code.token,label:'另一设备',publicKey:d.publicKey}))).rejects.toThrow('过期');const status=await agent.owner('status',{});expect(status.requests[0].code).toBe(claim.code);await agent.owner('approve',{requestId:claim.requestId});const approved=await agent.handle(await signed(d,'poll',{requestId:claim.requestId}));expect(approved.state).toBe('approved');const sample=await agent.handle(await signed(d,'snapshot',{connectionId:'conn'}));expect(sample.observedAt).toBe(observed);expect(sample.data.limits.rateLimits.primary.usedPercent).toBe(25);await agent.owner('revoke',{deviceId:d.id,connectionId:'conn'});await expect(agent.handle(await signed(d,'snapshot',{connectionId:'conn'}))).rejects.toThrow('未获授权');}));
  it('rejects expired tokens, denied requests, and tampered signatures',async()=>setup(async agent=>{const code=await share(agent),d=await device();agent.sessions.get(code.token).expiresAt=Date.now()-1;await expect(agent.handle(await signed(d,'claim',{token:code.token,label:'测试手机',publicKey:d.publicKey}))).rejects.toThrow('过期');const second=await share(agent),tampered=await signed(d,'claim',{token:second.token,label:'测试手机',publicKey:d.publicKey});tampered.label='被修改的名称';await expect(agent.handle(tampered)).rejects.toThrow('签名');const pending=await agent.handle(await signed(d,'claim',{token:second.token,label:'测试手机',publicKey:d.publicKey}));await agent.owner('deny',{requestId:pending.requestId});await expect(agent.handle(await signed(d,'poll',{requestId:pending.requestId}))).rejects.toThrow('拒绝');}));
  it('completes an encrypted two-client HTTP handshake and snapshot read without third-party credentials',async()=>setup(async agent=>{const server=createServer((req,res)=>void agent.remoteHandler(req,res));server.listen(0,'127.0.0.1');await once(server,'listening');try{const endpoint=`http://127.0.0.1:${server.address().port}/progress-relay/v1`,code=await agent.owner('share',{connection:{id:'conn',providerId:'codex',accountKey:raw.account.key},binding},endpoint),d=await device();const pending=await encrypted(endpoint,code.publicKey,await signed(d,'claim',{token:code.token,label:'加密测试手机',publicKey:d.publicKey}));expect(pending.state).toBe('pending');await agent.owner('approve',{requestId:pending.requestId});expect((await encrypted(endpoint,code.publicKey,await signed(d,'poll',{requestId:pending.requestId}))).state).toBe('approved');expect((await encrypted(endpoint,code.publicKey,await signed(d,'snapshot',{connectionId:'conn'}))).observedAt).toBe(observed);const wrong=await crypto.subtle.generateKey({name:'ECDH',namedCurve:'P-256'},false,['deriveKey']);await expect(encrypted(endpoint,enc(await crypto.subtle.exportKey('spki',wrong.publicKey)),await signed(d,'snapshot',{connectionId:'conn'}))).rejects.toThrow();}finally{server.closeAllConnections();server.close();}}));
  it('retains identity, approved device and encrypted upstream credentials across an Agent restart',async()=>setup(async(agent,directory)=>{const secret='fixture-secret-not-user';const server=createServer((req,res)=>{res.setHeader('Content-Type','application/json');res.statusCode=req.headers.authorization===`Bearer ${secret}`?200:401;res.end(JSON.stringify([{id:'q',name:'配额',kind:'range',value:42,max:100,meaning:'remaining',observed_at:observed}]));});server.listen(0,'127.0.0.1');await once(server,'listening');let restarted;try{const endpoint=`http://127.0.0.1:${server.address().port}/quota`;const code=await agent.owner('share',{connection:{id:'manual',providerId:'manual'},binding, snapshot:{data:[{id:'q',name:'配额',kind:'range',value:42,max:100,meaning:'remaining',observed_at:observed}]},upstream:{endpoint,method:'bearer',secret}},'http://127.0.0.1:5190/progress-relay/v1');const d=await device(),claim=await agent.handle(await signed(d,'claim',{token:code.token,label:'手机',publicKey:d.publicKey}));await agent.owner('approve',{requestId:claim.requestId});expect(await readFile(join(directory,'sources.enc'),'utf8')).not.toContain(secret);expect((await stat(join(directory,'identity.json'))).mode&0o777).toBe(0o600);agent.close();restarted=new PairingAgent({usage:async()=>raw},{directory});await restarted.ready;expect(restarted.deviceId).toBe(agent.deviceId);const result=await restarted.handle(await signed(d,'snapshot',{connectionId:'manual'}));expect(result.data[0].value).toBe(42);expect(result.observedAt).toBe(observed);}finally{restarted?.close();server.closeAllConnections();server.close();}}));
  it('blocks owner control from remote origins and without the required header',async()=>{const directory=await mkdtemp(join(tmpdir(),'progress-owner-')),bridge=createPairingMiddleware({usage:async()=>raw},{directory});await bridge.agent.ready;const server=createServer((req,res)=>void bridge.handler(req,res));server.listen(0,'127.0.0.1');await once(server,'listening');try{const endpoint=`http://127.0.0.1:${server.address().port}/api/pairing/status`;expect((await fetch(endpoint,{method:'POST',body:'{}'})).status).toBe(403);expect((await fetch(endpoint,{method:'POST',headers:{'X-Progress-Client':'pairing-v1',Origin:'https://example.com'},body:'{}'})).status).toBe(403);expect((await fetch(endpoint,{method:'POST',headers:{'X-Progress-Client':'pairing-v1'},body:'{}'})).status).toBe(200);}finally{server.closeAllConnections();server.close();bridge.close();await rm(directory,{recursive:true,force:true});}});
});

describe('Agent completion and resource safeguards',()=>{
  it('invalidates the approved pairing session after completion while keeping the device binding',async()=>setup(async agent=>{
    const code=await share(agent),d=await device(),claim=await agent.handle(await signed(d,'claim',{token:code.token,label:'手机',publicKey:d.publicKey}));
    await expect(agent.handle(await signed(d,'finish',{requestId:claim.requestId}))).rejects.toThrow('批准');
    await agent.owner('approve',{requestId:claim.requestId});
    expect(await agent.handle(await signed(d,'finish',{requestId:claim.requestId}))).toEqual({state:'complete'});
    await expect(agent.handle(await signed(d,'poll',{requestId:claim.requestId}))).rejects.toThrow('未获授权');
    expect((await agent.handle(await signed(d,'snapshot',{connectionId:'conn'}))).observedAt).toBe(observed);
  }));
  it('persists concurrent approvals atomically and coalesces overlapping source reads',async()=>setup(async(agent,directory)=>{
    const claims=[];for(let n=0;n<4;n++){const code=await share(agent),d=await device();claims.push(await agent.handle(await signed(d,'claim',{token:code.token,label:`手机 ${n}`,publicKey:d.publicKey})));}
    await Promise.all(claims.map(c=>agent.owner('approve',{requestId:c.requestId})));
    expect(JSON.parse(await readFile(join(directory,'devices.json'),'utf8'))).toHaveLength(4);
    let calls=0;agent.codex={usage:async()=>{calls++;await new Promise(resolve=>setTimeout(resolve,5));return raw;}};
    const source=agent.sources.get('conn');await Promise.all(Array.from({length:8},()=>agent.sample(source)));expect(calls).toBe(1);
  }));
  it('rejects malformed observations and supports declared provider IDs',async()=>setup(async agent=>{
    const metric={id:'q',name:'配额',kind:'range',value:50,max:100,meaning:'remaining',observed_at:observed};
    expect(agent.cleanSnapshot({data:[{...metric,min:100}]},'example')).toBeUndefined();
    expect(agent.cleanSnapshot({data:[{...metric,value:101}]},'example')).toBeUndefined();
    const code=await agent.owner('share',{connection:{id:'example',providerId:'example'},binding,snapshot:{data:[metric]}},'http://127.0.0.1:5190/progress-relay/v1');expect(code.connectionId).toBe('example');
    const d=await device(),invalid=await signed(d,'claim',{token:code.token,label:'手机',publicKey:d.publicKey});delete invalid.timestamp;await expect(agent.handle(invalid)).rejects.toThrow('过期');
  }));
  it('caps relay requests before cryptography and never returns internal exception text',async()=>setup(async agent=>{
    const server=createServer((req,res)=>void agent.remoteHandler(req,res));server.listen(0,'127.0.0.1');await once(server,'listening');
    try{const endpoint=`http://127.0.0.1:${server.address().port}/progress-relay/v1`,code=await share(agent),d=await device();
      const claim=await agent.handle(await signed(d,'claim',{token:code.token,label:'手机',publicKey:d.publicKey}));await agent.owner('approve',{requestId:claim.requestId});
      agent.codex={usage:async()=>{throw new Error('fixture-secret-in-internal-error');}};
      const response=await encrypted(endpoint,code.publicKey,await signed(d,'snapshot',{connectionId:'conn'}));expect(response.error).not.toContain('fixture-secret');
      agent.rates.set('127.0.0.1',{count:120,until:Date.now()+60000});expect((await fetch(endpoint,{method:'POST',body:'{}'})).status).toBe(429);
    }finally{server.closeAllConnections();server.close();}
  }));
});
