import { describe, expect, it } from 'vitest';
import { createServer } from 'node:http';
import { once } from 'node:events';
import { demoWorkspace, emptyWorkspace, upgradeWorkspace, builtins } from '../src/core/components';
import { clone, cardsBundle, removeCards, restoreCards } from '../src/core/model';
import { migrateFolders, folderWorkspace, moveCard, duplicateFolder } from '../src/core/folders';
import { resolveGrid, resolvePlacements, commitPlacements, fillHoles, intersects } from '../src/core/grid';
import { anchorMenu, resistedDistance, jiggleParameters } from '../src/core/gestures';
import { adaptPdmQuota, newestSnapshot, chooseConnection, readInstanceConnections, type ConnectionSample, safeEndpoint, sourceSignature, sampleCacheKey } from '../src/core/providers';
import { parsePairingCode } from '../src/core/pairing';
import { bindRelay } from '../src/ui/Pairing';
import { importFile, packageWorkspace, mergeWorkspace, portableWorkspace } from '../src/core/packages';
import { assertWorkspace, assertComponent } from '../src/core/validation';
const observed='2026-10-07T12:00:00Z';
const pdm=[{id:'short',name:'短周期',kind:'range',value:25,max:100,meaning:'used',observed_at:observed,reset_at:'2026-10-07T14:00:00Z',window_minutes:300},{id:'long',name:'每周',kind:'range',value:60,max:100,meaning:'remaining',observed_at:observed}];
describe('square geometry and interaction',()=>{
  it('keeps 1×1 square throughout continuous widths and crosses only integer column thresholds',()=>{for(let width=240;width<=2200;width+=7){const g=resolveGrid(width);expect(g.rowHeight).toBe(g.cell);expect(g.cell).toBeLessThanOrEqual(336);expect(g.cell).toBeGreaterThanOrEqual(168);expect(g.columns).toBe(Math.floor(g.columns));expect(g.columns*g.cell+(g.columns-1)*g.gap+2*g.inset).toBeCloseTo(width);expect(g.gap).toBeGreaterThanOrEqual(12);expect(g.gap).toBeLessThanOrEqual(20);}});
  it('anchors menus to card bounds, flips and clamps to the content and viewport',()=>{expect(anchorMenu({left:200,right:360,top:140,bottom:300},{left:180,right:1200,top:88,bottom:700})).toEqual({x:370,y:140});const p=anchorMenu({left:980,right:1160,top:650,bottom:810},{left:180,right:1200,top:88,bottom:700});expect(p.x).toBe(764);expect(p.y+282).toBeLessThanOrEqual(700);const narrow=anchorMenu({left:16,right:180,top:140,bottom:310},{left:12,right:378,top:88,bottom:700});expect(narrow.x).toBeGreaterThanOrEqual(12);expect(narrow.x+206).toBeLessThanOrEqual(378);});
  it('uses light initial resistance followed by one-to-one motion and stable size-dependent jiggle',()=>{expect(resistedDistance(6)).toBeCloseTo(3.3);expect(resistedDistance(20)-resistedDistance(19)).toBe(1);expect(resistedDistance(-20)).toBe(-resistedDistance(20));const p=jiggleParameters('card',19,1);expect(p).toEqual(jiggleParameters('card',19,1));expect(p.rotationMs).toBeGreaterThanOrEqual(115);expect(p.rotationMs).toBeLessThanOrEqual(165);expect(p.rotation).toBeGreaterThan(jiggleParameters('card',19,8).rotation);});
  it('fills earlier holes stably without overlap and preserves a pinned move',()=>{const w=demoWorkspace();const original=resolvePlacements(w,4);const compacted=fillHoles(original.slice(1),4);expect(compacted[0]).toMatchObject({column:0,row:0});for(const a of compacted)for(const b of compacted)if(a!==b)expect(intersects(a,b)).toBe(false);expect(fillHoles(original,4,original[0].id)[0]).toEqual(original[0]);});
});
describe('folders, connection references and portable metadata',()=>{
  it('migrates old workspaces without changing values and keeps grid state independent per folder',()=>{const old=demoWorkspace();delete old.folders;delete old.autoFill;old.cards.forEach(c=>delete c.folderId);const migrated=upgradeWorkspace(old);expect(migrated.autoFill).toBe(true);expect(migrated.cards.map(c=>c.folderId)).toEqual(Array(6).fill('default'));expect(migrated.instances).toEqual(old.instances);const next=duplicateFolder(migrated,'default');expect(resolvePlacements(folderWorkspace(next,next.folders![1].id),4).map(p=>[p.column,p.row])).toEqual(resolvePlacements(folderWorkspace(next,'default'),4).map(p=>[p.column,p.row]));});
  it('moves only card membership and placement, retaining connections and source values',()=>{const w=duplicateFolder(demoWorkspace(),'default'),card=w.cards[0];const next=moveCard(w,card.id,w.folders![1].id);expect(next.instances).toBe(w.instances);expect(next.connections).toBe(w.connections);expect(next.components).toBe(w.components);expect(next.cards.find(c=>c.id===card.id)?.folderId).toBe(w.folders![1].id);});
  it('commits one folder without moving or reordering cards in another folder',()=>{const w=duplicateFolder(demoWorkspace(),'default');const other=clone(folderWorkspace(w,w.folders![1].id).cards);const next=commitPlacements(w,resolvePlacements(folderWorkspace(w,'default'),3),3);expect(folderWorkspace(next,w.folders![1].id).cards).toEqual(other);});
  it('exports no credentials or caches, restores folder membership, and remaps conflicting connection IDs',async()=>{const w=demoWorkspace(),i=w.instances[0];w.connections=[{id:'conn',providerId:'manual',method:'bearer',kind:'direct',label:'测试连接',endpoint:'https://example.com/quota',credentialRef:'private-ref',priority:0}];i.connectionIds=['conn'];(w as any).refreshToken='fixture-secret';(i as any).token='fixture-secret';const bundle=cardsBundle(w,[w.cards[0].id]);const portable=portableWorkspace(bundle);expect(JSON.stringify(portable)).not.toMatch(/fixture-secret|private-ref|example.com/);const restored=(await importFile('folder.progresspack',new Uint8Array(await packageWorkspace(bundle)).buffer)).workspace!;expect(restored.cards[0].folderId).toBe('default');expect(restored.connections![0].reconnect).toBe(true);const merged=mergeWorkspace(w,restored,'rename');const copied=merged.instances.find(x=>x.id!==i.id&&x.connectionIds?.length)!;expect(copied.connectionIds![0]).not.toBe('conn');assertWorkspace(merged);});
  it('restores deleted bindings on undo and rejects plaintext connection secrets',()=>{const w=demoWorkspace();w.connections=[{id:'conn',providerId:'manual',kind:'direct',method:'read-only-url',label:'服务',priority:0}];w.instances[0].connectionIds=['conn'];const removed=removeCards(w,[w.cards[0].id]);expect(removed.connections).toHaveLength(0);const restored=restoreCards(removed,w,[w.cards[0].id]);expect(restored.connections).toHaveLength(1);assertWorkspace(restored);(restored.connections![0] as any).token='fixture-secret';expect(()=>assertWorkspace(restored)).toThrow('凭据');});
  it('adds a relay as backup or explicitly replaces a binding without silently overwriting cards',()=>{const w=demoWorkspace();const component=builtins.find(c=>c.manifest.runtime.type==='provider_quota')!;const binding=emptyWorkspace();binding.instances.push({id:'source',componentId:component.manifest.id,name:'配额',config:{},createdAt:observed});binding.cards.push({id:'source-card',instanceId:'source',metricId:'provider-quota',renderer:'quota',color:'#197b65',folderId:'default'});const relay={id:'relay',providerId:'manual',kind:'relay',method:'pairing',label:'电脑',sourceConnectionId:'remote',priority:10} as const;const target={...binding.instances[0],id:'target',connectionIds:['direct']};w.connections=[{id:'direct',providerId:'manual',kind:'direct',method:'read-only-url',label:'直连',priority:0}];w.instances.push(target);expect(bindRelay(w,relay,binding,target,'backup','default').instances.at(-1)?.connectionIds).toEqual(['direct','relay']);expect(bindRelay(w,relay,binding,target,'replace','default').instances.at(-1)?.connectionIds).toEqual(['relay']);expect(bindRelay(w,relay,binding,target,'new','default').cards).toHaveLength(7);});
});
describe('provider truthfulness and source selection',()=>{
  it('maps independent real windows without requiring or inventing reset times',()=>{const q=adaptPdmQuota(pdm,'manual','服务');expect(q.groups[0].windows.map(w=>w.remainingPercent)).toEqual([75,60]);expect(q.groups[0].windows[0].resetsAt).toBe(Date.parse('2026-10-07T14:00:00Z')/1000);expect(q.groups[0].windows[1].resetsAt).toBeNull();expect(q.observedAt).toBe(observed);});
  it('rejects missing observations, unknown semantics and over-range quota instead of fabricating freshness',()=>{for(const m of [{...pdm[0],observed_at:undefined},{...pdm[0],meaning:'completed'},{...pdm[0],value:101}])expect(()=>adaptPdmQuota([m],'manual','服务')).toThrow();for(const endpoint of ['http://example.com/quota','https://user:pass@example.com/quota','https://example.com/quota?token=secret'])expect(()=>safeEndpoint(endpoint)).toThrow();});
  it('preserves a newer observation even when an older relay packet arrives later',()=>{const old={metrics:[],observedAt:observed,receivedAt:'2026-10-07T12:30:00Z'};const current={metrics:[],observedAt:'2026-10-07T12:10:00Z',receivedAt:'2026-10-07T12:11:00Z'};expect(newestSnapshot(current,old).observedAt).toBe(current.observedAt);expect(newestSnapshot(current,old).receivedAt).toBe(current.receivedAt);});
  it('selects availability, observation freshness, priority and latency, with explicit strategy restrictions',()=>{const connections=[{id:'direct',kind:'direct',priority:0},{id:'relay',kind:'relay',priority:10}] as any;const a={metrics:[],connectionId:'direct',observedAt:observed,receivedAt:observed,sourceDevice:'手机',latency:10},b={...a,connectionId:'relay',observedAt:'2026-10-07T12:02:00Z',latency:100};expect(chooseConnection([a,b] as ConnectionSample[],connections)?.connectionId).toBe('relay');expect(chooseConnection([a,b] as ConnectionSample[],connections,'direct')?.connectionId).toBe('direct');expect(chooseConnection([{...b,observedAt:observed},a] as ConnectionSample[],connections)?.connectionId).toBe('direct');});
  it('falls back to a reachable real read-only service when another binding fails',async()=>{const server=createServer((req,res)=>{res.setHeader('Content-Type','application/json');res.statusCode=req.url==='/bad'?503:200;res.end(JSON.stringify(pdm));});server.listen(0,'127.0.0.1');await once(server,'listening');try{const port=(server.address() as any).port,w=emptyWorkspace();w.connections=['bad','good'].map(id=>({id,providerId:'manual',method:'read-only-url',kind:'direct',endpoint:`http://127.0.0.1:${port}/${id}`,label:id,priority:0}));const i={id:'test',componentId:'dev.progress.connected-quota',name:'配额',config:{},createdAt:observed,connectionIds:['bad','good']};const snapshot=await readInstanceConnections(w,i);expect(snapshot.connectionId).toBe('good');expect(snapshot.observedAt).toBe(observed);expect(snapshot.receivedAt).not.toBe(observed);}finally{server.close();}});
  it('accepts installed provider declarations but rejects unsupported OAuth and reserved identities',()=>{const c=clone(builtins.find(c=>c.manifest.runtime.type==='provider_quota')!);c.manifest.id='dev.example.provider';c.manifest.quotaProvider={id:'example',name:'Example',connectionMethods:['api-key','pairing'],helpUrl:'https://example.com/docs',credentialInstructions:['在服务端创建只读 Key。'],requiredScopes:['quota:read']};assertComponent(c);c.manifest.quotaProvider.connectionMethods=['oauth'];expect(()=>assertComponent(c)).toThrow('不兼容');});
  it('rejects expired or credential-bearing QR payloads',()=>{const code={schema:'progress/pairing/v1',token:'a'.repeat(64),expiresAt:Date.now()+60000,sourceDevice:'电脑',sourceDeviceId:'source',connectionId:'conn',cardId:'card',endpoint:'http://127.0.0.1:5190/progress-relay/v1',publicKey:'pinned'};expect(parsePairingCode(JSON.stringify(code)).connectionId).toBe('conn');expect(()=>parsePairingCode(JSON.stringify({...code,tokenSecret:'bad'}))).toThrow();expect(()=>parsePairingCode(JSON.stringify({...code,expiresAt:Date.now()-1}))).toThrow();});
});

describe('v0.5 continuation regressions',()=>{
  it('isolates cache identity when credentials, account, endpoint or strategy change while retaining unrelated folder edits',()=>{
    const w=emptyWorkspace();const instance={id:'quota',componentId:'dev.progress.connected-quota',name:'配额',config:{},createdAt:observed,connectionIds:['source']};
    w.connections=[{id:'source',providerId:'manual',method:'bearer',kind:'direct',label:'服务',endpoint:'https://example.com/quota',credentialRef:'first',priority:0}];
    const initial=sampleCacheKey(w,instance);
    for(const patch of [{credentialRef:'second'},{endpoint:'https://example.com/other'},{accountKey:'new-account'}])expect(sampleCacheKey({...w,connections:[{...w.connections[0],...patch}]},instance)).not.toBe(initial);
    expect(sampleCacheKey(w,{...instance,connectionStrategy:'relay'})).not.toBe(initial);
    expect(sourceSignature({...w,folders:[{id:'other',name:'工作',icon:'folder',color:'#197b65'}]},instance)).toBe(sourceSignature(w,instance));
  });
  it('drops unexpected credential fields from provider metrics and secondary data',()=>{
    const q=adaptPdmQuota([{...pdm[0],accessToken:'fixture-secret',secondary:[{role:'count',value:1,password:'fixture-secret'}]}],'manual','服务');
    expect(JSON.stringify(q)).not.toContain('fixture-secret');expect(q.metrics[0].secondary).toEqual([{role:'count',value:1}]);
  });
});

  it('blocks credential-bearing legacy configs before creating an export',()=>{const w=demoWorkspace();w.instances[0].config.apiKey='fixture-secret';expect(()=>portableWorkspace(w)).toThrow('凭据');delete w.instances[0].config.apiKey;w.instances[0].config.endpoint='https://example.com/quota?access_token=fixture-secret';expect(()=>portableWorkspace(w)).toThrow('凭据');});
